import type { LandingThemeContent } from "@/src/components/landing/types";
import type { EliteGlobalStyles } from "@/src/components/landing/elite-config";

export const SAMPLE_GLOBAL_STYLES: EliteGlobalStyles = {
  primaryColor: "#ccff00",
  backgroundColor: "#0a0a0a",
  textColor: "#ffffff",
  fontFamilyHeading: "Inter, sans-serif",
  fontFamilyBody: "Inter, sans-serif",
  borderRadius: "md",
};

const SAMPLE_HERO = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1600&auto=format&fit=crop";
const SAMPLE_AVATAR = "https://images.unsplash.com/photo-1607499699372-8cf01c1e8b75?q=80&w=400&auto=format&fit=crop";
const SAMPLE_BEFORE = "https://images.unsplash.com/photo-1583500178690-f7fd39c5691d?q=80&w=600&auto=format&fit=crop";
const SAMPLE_AFTER = "https://images.unsplash.com/photo-1583500178690-f7fd39c5691d?q=80&w=600&auto=format&fit=crop";

export const SAMPLE_BLOCK_CONTENT: LandingThemeContent = {
  domain: "demo",
  brandName: "Atlas Fit",
  bio: "Premium online koçluk. Sonuç odaklı sistem.",
  logo: null,
  heroImage: SAMPLE_HERO,
  heroImageOriginalUrl: SAMPLE_HERO,
  heroImageDesktopUrl: SAMPLE_HERO,
  heroImageMobileUrl: SAMPLE_HERO,
  heroImageBlurDataUrl: null,
  heroImageCutoutUrl: null,
  heroFocalX: 50,
  heroFocalY: 35,
  heroMode: "photo",
  heroImageDark: false,
  email: "demo@example.com",
  authUrl: "/auth",
  whatsappUrl: "https://wa.me/905555555555",
  whatsappNumber: "+90 555 555 55 55",
  packages: [
    {
      id: "p1",
      name: "Başlangıç",
      description: "Yeni başlayanlar için 4 haftalık plan",
      duration: 4,
      price: 1499,
      currency: "TRY",
      features: ["Kişisel program", "Beslenme planı", "Haftalık check-in"],
    },
    {
      id: "p2",
      name: "Profesyonel",
      description: "Hedef odaklı 12 haftalık dönüşüm",
      duration: 12,
      price: 3999,
      currency: "TRY",
      features: ["1:1 koçluk", "Detaylı makro takibi", "Video form analizi", "WhatsApp desteği"],
    },
    {
      id: "p3",
      name: "Elite",
      description: "Tam donanımlı 6 ay program",
      duration: 24,
      price: 8999,
      currency: "TRY",
      features: ["Sınırsız destek", "Haftalık görüşme", "Premium kaynaklar", "Özel beslenme tarifleri"],
    },
  ],
  testimonials: [
    {
      id: "tm1",
      clientName: "Mert Aydın",
      role: "Yazılımcı",
      quote:
        "12 haftada 14 kilo verdim, enerjim hiç bu kadar yüksek olmamıştı. Program tam bana göreydi.",
      rating: 5,
      avatar: null,
    },
    {
      id: "tm2",
      clientName: "Selin Kaya",
      role: "Öğretmen",
      quote:
        "Daha önce defalarca denedim ama ilk kez sürdürülebilir bir sistem buldum. Koçumun desteği muhteşemdi.",
      rating: 5,
      avatar: null,
    },
    {
      id: "tm3",
      clientName: "Burak Demir",
      role: "Online Danışan",
      quote:
        "8 haftada hem kondisyonum hem de özgüvenim arttı. Herkese tavsiye ederim.",
      rating: 4,
      avatar: null,
    },
  ],
  transformations: [
    {
      id: "t1",
      clientName: "Ayşe K.",
      beforePhoto: SAMPLE_BEFORE,
      afterPhoto: SAMPLE_AFTER,
      duration: "12 hafta",
      description: "12 haftada -8kg",
    },
    {
      id: "t2",
      clientName: "Mehmet Y.",
      beforePhoto: SAMPLE_BEFORE,
      afterPhoto: SAMPLE_AFTER,
      duration: "16 hafta",
      description: "16 haftada +6kg kas",
    },
    {
      id: "t3",
      clientName: "Zeynep A.",
      beforePhoto: SAMPLE_BEFORE,
      afterPhoto: SAMPLE_AFTER,
      duration: "8 hafta",
      description: "8 haftada -5kg",
    },
  ],
  studentCount: 247,
  transformationCount: 89,
  programCount: 156,
  title: "Atlas Fit",
  tagline: "Premium online koçluk. Sonuç odaklı sistem.",
  instagramUrl: "https://instagram.com/atlasfit",
  facebookUrl: "https://facebook.com/atlasfit",
  tiktokUrl: "https://tiktok.com/@atlasfit",
  youtubeUrl: undefined,
  linkedinUrl: undefined,
  twitterUrl: undefined,
  faqs: [
    { id: "f1", question: "Programa nasıl başlarım?", answer: "Paketinizi seçtikten sonra koçunuz size 24 saat içinde dönüş yapar." },
    { id: "f2", question: "Ne kadar sürede sonuç alırım?", answer: "Disiplininize bağlı olarak 4-6 hafta içinde fark hissedersiniz." },
    { id: "f3", question: "Spor salonu zorunlu mu?", answer: "Hayır, ev ortamı ve ekipman seviyenize göre alternatif programlar mevcut." },
  ],
  contactPhone: "+90 555 555 55 55",
  businessAddress: "İstanbul, Türkiye",
  legalSlugs: ["gizlilik", "kvkk", "kullanim"],
  landingConfig: null,
  socialLinks: {
    instagram: "https://instagram.com/atlasfit",
    facebook: "https://facebook.com/atlasfit",
    tiktok: "https://tiktok.com/@atlasfit",
  },
  headingFont: null,
  bodyFont: null,
  landingTexts: {
    heroHeadline: "Yeni Bedeniniz Sizi Bekliyor",
    heroSubtitle: "Bilimsel temele dayalı kişisel program ile hedeflerinize en hızlı yoldan ulaşın.",
    ctaPrimaryText: "Hemen Başla",
    ctaSecondaryText: "Detayları Gör",
    stat1Label: "Aktif Öğrenci",
    stat1Value: "247+",
    stat2Label: "Başarı Oranı",
    stat2Value: "%96",
    stat3Label: "Toplam Dönüşüm",
    stat3Value: "89",
    transformationsTitle: "Öğrenci Sonuçları",
    systemTitle: "Sistem Nasıl İşler?",
    system1Title: "Ön Değerlendirme",
    system1Description: "Detaylı vücut analizi, hedef ve geçmiş incelenir.",
    system2Title: "Kişisel Plan",
    system2Description: "Size özel antrenman ve beslenme şablonu hazırlanır.",
    system3Title: "Aksiyon ve Takip",
    system3Description: "Haftalık check-in ile süreç optimize edilir.",
    packagesTitle: "Paketler",
    packagesSubtitle: "Hedeflerinize uygun planı seçin.",
    faqTitle: "Sıkça Sorulan Sorular",
    footerTagline: "Sonuç odaklı premium online koçluk.",
    aboutTitle: "Koçunuzla Tanışın",
    aboutBio1: "10 yılı aşkın profesyonel deneyimle, size özel programlar tasarlıyorum.",
    aboutBio2: "Hedef odaklı, sürdürülebilir ve bilimsel temellere dayanan yaklaşımım.",
    aboutRole: "Kurucu / Ana Koç",
  },
  eliteConfig: null,
};
