// Hazır egzersiz veritabanı - 250+ Türkçe fitness hareketi
export const EXERCISE_DATABASE = [
  // ═══ GÖĞÜS ═══
  { name: "Bench Press (Düz Bank)", category: "Göğüs", description: "Düz bankta barbell ile göğüs presi" },
  { name: "İncline Bench Press", category: "Göğüs", description: "Eğimli bankta barbell ile üst göğüs presi" },
  { name: "Decline Bench Press", category: "Göğüs", description: "Ters eğimli bankta alt göğüs presi" },
  { name: "Dumbbell Bench Press", category: "Göğüs", description: "Düz bankta dumbbell ile göğüs presi" },
  { name: "İncline Dumbbell Press", category: "Göğüs", description: "Eğimli bankta dumbbell ile üst göğüs presi" },
  { name: "Dumbbell Fly", category: "Göğüs", description: "Düz bankta dumbbell fly hareketi" },
  { name: "İncline Dumbbell Fly", category: "Göğüs", description: "Eğimli bankta dumbbell fly" },
  { name: "Cable Crossover", category: "Göğüs", description: "Kablo makinesinde çapraz göğüs hareketi" },
  { name: "Pec Deck (Kelebek)", category: "Göğüs", description: "Pec deck makinesinde kelebek hareketi" },
  { name: "Push-Up (Şınav)", category: "Göğüs", description: "Vücut ağırlığı ile klasik şınav" },
  { name: "Diamond Push-Up", category: "Göğüs", description: "Elmas tutuşlu şınav" },
  { name: "Chest Dip", category: "Göğüs", description: "Paralel barda göğüs dip" },
  { name: "Machine Chest Press", category: "Göğüs", description: "Makine ile göğüs presi" },
  { name: "Svend Press", category: "Göğüs", description: "Plaka sıkıştırmalı göğüs presi" },
  { name: "Landmine Press", category: "Göğüs", description: "Landmine ile göğüs presi" },

  // ═══ SIRT ═══
  { name: "Deadlift", category: "Sırt", description: "Barbell ile klasik deadlift" },
  { name: "Barbell Row", category: "Sırt", description: "Barbell ile eğilerek kürek çekme" },
  { name: "Dumbbell Row", category: "Sırt", description: "Tek kol dumbbell kürek çekme" },
  { name: "Lat Pulldown", category: "Sırt", description: "Lat pulldown makinesinde geniş tutuş" },
  { name: "Close Grip Lat Pulldown", category: "Sırt", description: "Dar tutuşlu lat pulldown" },
  { name: "Pull-Up (Barfiks)", category: "Sırt", description: "Vücut ağırlığı ile barfiks" },
  { name: "Chin-Up", category: "Sırt", description: "Avuç içi size dönük barfiks" },
  { name: "Seated Cable Row", category: "Sırt", description: "Oturarak kablo kürek çekme" },
  { name: "T-Bar Row", category: "Sırt", description: "T-bar ile kürek çekme" },
  { name: "Cable Face Pull", category: "Sırt", description: "Kablo ile yüze çekiş" },
  { name: "Straight Arm Pulldown", category: "Sırt", description: "Düz kol lat pulldown" },
  { name: "Rack Pull", category: "Sırt", description: "Rack'ten kısmi deadlift" },
  { name: "Hyperextension", category: "Sırt", description: "Alt sırt uzatma hareketi" },
  { name: "Reverse Fly (Makine)", category: "Sırt", description: "Makine ile ters fly" },
  { name: "Pendlay Row", category: "Sırt", description: "Yerden barbell kürek çekme" },
  { name: "Meadows Row", category: "Sırt", description: "Landmine ile tek kol kürek" },
  { name: "Inverted Row", category: "Sırt", description: "Ters gövde çekişi" },
  { name: "Sumo Deadlift", category: "Sırt", description: "Geniş duruşlu deadlift" },

  // ═══ OMUZ ═══
  { name: "Overhead Press (Military)", category: "Omuz", description: "Ayakta barbell omuz presi" },
  { name: "Dumbbell Shoulder Press", category: "Omuz", description: "Oturarak dumbbell omuz presi" },
  { name: "Arnold Press", category: "Omuz", description: "Arnold Schwarzenegger omuz presi" },
  { name: "Lateral Raise", category: "Omuz", description: "Dumbbell ile yan kaldırma" },
  { name: "Front Raise", category: "Omuz", description: "Dumbbell ile ön kaldırma" },
  { name: "Rear Delt Fly", category: "Omuz", description: "Arka omuz fly hareketi" },
  { name: "Cable Lateral Raise", category: "Omuz", description: "Kablo ile yan kaldırma" },
  { name: "Upright Row", category: "Omuz", description: "Dik çekiş (barbell/dumbbell)" },
  { name: "Machine Shoulder Press", category: "Omuz", description: "Makine ile omuz presi" },
  { name: "Shrug (Barbell)", category: "Omuz", description: "Barbell ile trapez kaldırma" },
  { name: "Dumbbell Shrug", category: "Omuz", description: "Dumbbell ile trapez kaldırma" },
  { name: "Lu Raise", category: "Omuz", description: "Lateral + front raise kombinasyonu" },
  { name: "Behind Neck Press", category: "Omuz", description: "Ense arkası omuz presi" },
  { name: "Plate Front Raise", category: "Omuz", description: "Plaka ile ön kaldırma" },

  // ═══ BICEPS ═══
  { name: "Barbell Curl", category: "Biceps", description: "Barbell ile biceps curl" },
  { name: "Dumbbell Curl", category: "Biceps", description: "Dumbbell ile biceps curl" },
  { name: "Hammer Curl", category: "Biceps", description: "Nötr tutuşlu dumbbell curl" },
  { name: "Preacher Curl", category: "Biceps", description: "Scott sehpasında curl" },
  { name: "İncline Dumbbell Curl", category: "Biceps", description: "Eğimli bankta dumbbell curl" },
  { name: "Concentration Curl", category: "Biceps", description: "Oturarak konsantrasyon curl" },
  { name: "Cable Curl", category: "Biceps", description: "Kablo ile biceps curl" },
  { name: "EZ Bar Curl", category: "Biceps", description: "EZ bar ile biceps curl" },
  { name: "Spider Curl", category: "Biceps", description: "Eğimli bankta spider curl" },
  { name: "Reverse Curl", category: "Biceps", description: "Ters tutuşlu curl (ön kol)" },
  { name: "21s Curl", category: "Biceps", description: "7-7-7 tekrar biceps curl" },
  { name: "Cross Body Hammer Curl", category: "Biceps", description: "Çapraz hammer curl" },

  // ═══ TRICEPS ═══
  { name: "Triceps Pushdown (Kablo)", category: "Triceps", description: "Kablo ile triceps pushdown" },
  { name: "Rope Pushdown", category: "Triceps", description: "İp ile triceps pushdown" },
  { name: "Overhead Triceps Extension", category: "Triceps", description: "Başın üstünde triceps uzatma" },
  { name: "Skull Crusher", category: "Triceps", description: "Düz bankta EZ bar skull crusher" },
  { name: "Dumbbell Kickback", category: "Triceps", description: "Dumbbell ile triceps kickback" },
  { name: "Close Grip Bench Press", category: "Triceps", description: "Dar tutuşlu bench press" },
  { name: "Triceps Dip", category: "Triceps", description: "Paralel barda triceps dip" },
  { name: "Bench Dip", category: "Triceps", description: "Bank üzerinde triceps dip" },
  { name: "Cable Overhead Extension", category: "Triceps", description: "Kablo ile baş üstü uzatma" },
  { name: "JM Press", category: "Triceps", description: "JM Press (skull crusher + close grip)" },
  { name: "Single Arm Pushdown", category: "Triceps", description: "Tek kol kablo pushdown" },

  // ═══ BACAK ═══
  { name: "Squat (Barbell)", category: "Bacak", description: "Barbell ile back squat" },
  { name: "Front Squat", category: "Bacak", description: "Barbell ile front squat" },
  { name: "Goblet Squat", category: "Bacak", description: "Dumbbell/kettlebell ile goblet squat" },
  { name: "Leg Press", category: "Bacak", description: "Leg press makinesinde bacak presi" },
  { name: "Hack Squat", category: "Bacak", description: "Hack squat makinesi" },
  { name: "Bulgarian Split Squat", category: "Bacak", description: "Bulgar split squat" },
  { name: "Lunge (Dumbbell)", category: "Bacak", description: "Dumbbell ile hamle" },
  { name: "Walking Lunge", category: "Bacak", description: "Yürüyerek hamle" },
  { name: "Leg Extension", category: "Bacak", description: "Leg extension makinesi (quadriceps)" },
  { name: "Leg Curl (Yatarak)", category: "Bacak", description: "Yatarak leg curl (hamstring)" },
  { name: "Seated Leg Curl", category: "Bacak", description: "Oturarak leg curl" },
  { name: "Romanian Deadlift (RDL)", category: "Bacak", description: "Romen deadlift (hamstring)" },
  { name: "Stiff Leg Deadlift", category: "Bacak", description: "Sert bacak deadlift" },
  { name: "Calf Raise (Ayakta)", category: "Bacak", description: "Ayakta baldır kaldırma" },
  { name: "Seated Calf Raise", category: "Bacak", description: "Oturarak baldır kaldırma" },
  { name: "Smith Machine Squat", category: "Bacak", description: "Smith machine squat" },
  { name: "Sissy Squat", category: "Bacak", description: "Sissy squat (quadriceps)" },
  { name: "Step Up", category: "Bacak", description: "Bank/kutu üzerine adım atma" },
  { name: "Box Squat", category: "Bacak", description: "Kutu üzerine oturarak squat" },
  { name: "Pistol Squat", category: "Bacak", description: "Tek bacak squat" },
  { name: "Good Morning", category: "Bacak", description: "Barbell good morning" },
  { name: "Hip Thrust", category: "Bacak", description: "Barbell ile hip thrust" },
  { name: "Glute Bridge", category: "Bacak", description: "Kalça köprüsü" },
  { name: "Single Leg RDL", category: "Bacak", description: "Tek bacak Romen deadlift" },
  { name: "Pendulum Squat", category: "Bacak", description: "Pendulum squat makinesi" },

  // ═══ KALÇA ═══
  { name: "Hip Thrust (Barbell)", category: "Kalça", description: "Barbell ile hip thrust" },
  { name: "Cable Kickback", category: "Kalça", description: "Kablo ile geriye tekme" },
  { name: "Glute Bridge (Dumbbell)", category: "Kalça", description: "Dumbbell ile kalça köprüsü" },
  { name: "Sumo Squat", category: "Kalça", description: "Geniş duruşlu squat" },
  { name: "Fire Hydrant", category: "Kalça", description: "Dört ayak üzerinde yan kaldırma" },
  { name: "Donkey Kick", category: "Kalça", description: "Dört ayak üzerinde geriye tekme" },
  { name: "Abduction Machine", category: "Kalça", description: "Dış bacak açma makinesi" },
  { name: "Adduction Machine", category: "Kalça", description: "İç bacak kapama makinesi" },
  { name: "Frog Pump", category: "Kalça", description: "Kurbağa pompası (kalça)" },
  { name: "Reverse Lunge", category: "Kalça", description: "Geriye hamle" },
  { name: "Curtsy Lunge", category: "Kalça", description: "Çapraz hamle" },

  // ═══ KARIN ═══
  { name: "Crunch", category: "Karın", description: "Klasik karın sıkıştırma" },
  { name: "Sit-Up (Mekik)", category: "Karın", description: "Tam mekik hareketi" },
  { name: "Plank", category: "Karın", description: "Düz plank (isometrik)" },
  { name: "Side Plank", category: "Karın", description: "Yan plank" },
  { name: "Leg Raise (Yere Yatarak)", category: "Karın", description: "Yerde yatarak bacak kaldırma" },
  { name: "Hanging Leg Raise", category: "Karın", description: "Asılı bacak kaldırma" },
  { name: "Russian Twist", category: "Karın", description: "Oturarak gövde rotasyonu" },
  { name: "Cable Crunch", category: "Karın", description: "Kablo ile diz çökerek karın" },
  { name: "Ab Wheel Rollout", category: "Karın", description: "Ab wheel ile ileri geri" },
  { name: "Mountain Climber", category: "Karın", description: "Dağcı hareketi" },
  { name: "Bicycle Crunch", category: "Karın", description: "Bisiklet karın hareketi" },
  { name: "V-Up", category: "Karın", description: "V şeklinde karın kaldırma" },
  { name: "Dead Bug", category: "Karın", description: "Dead bug hareketi (core stabilite)" },
  { name: "Pallof Press", category: "Karın", description: "Kablo ile anti-rotasyon presi" },
  { name: "Dragon Flag", category: "Karın", description: "Bank üzerinde dragon flag" },
  { name: "Decline Crunch", category: "Karın", description: "Eğimli bankta crunch" },
  { name: "Woodchop (Kablo)", category: "Karın", description: "Kablo ile odun kesme hareketi" },
  { name: "Toe Touch", category: "Karın", description: "Yatarak ayak parmağına dokunma" },

  // ═══ KARDİO ═══
  { name: "Koşu Bandı", category: "Kardio", description: "Koşu bandında koşu/yürüyüş" },
  { name: "Eliptik Bisiklet", category: "Kardio", description: "Eliptik trainer" },
  { name: "Bisiklet (Statik)", category: "Kardio", description: "Sabit bisiklet" },
  { name: "Kürek Çekme Makinesi", category: "Kardio", description: "Rowing machine" },
  { name: "Merdiven Tırmanma", category: "Kardio", description: "StairMaster" },
  { name: "Jump Rope (İp Atlama)", category: "Kardio", description: "İp atlama" },
  { name: "Burpee", category: "Kardio", description: "Tam vücut burpee" },
  { name: "Box Jump", category: "Kardio", description: "Kutu üzerine atlama" },
  { name: "Battle Rope", category: "Kardio", description: "Savaş ipi hareketi" },
  { name: "Kettlebell Swing", category: "Kardio", description: "Kettlebell salınım" },
  { name: "Assault Bike", category: "Kardio", description: "Air bike / Assault bike" },
  { name: "Jumping Jack", category: "Kardio", description: "Açık-kapalı atlama" },
  { name: "High Knees", category: "Kardio", description: "Yüksek diz çekme" },
  { name: "Sprint", category: "Kardio", description: "Kısa mesafe sprint" },
  { name: "Sled Push/Pull", category: "Kardio", description: "Kızak itme/çekme" },

  // ═══ ESNEKLİK ═══
  { name: "Hamstring Stretch", category: "Esneklik", description: "Arka bacak germe" },
  { name: "Quad Stretch", category: "Esneklik", description: "Ön bacak germe" },
  { name: "Hip Flexor Stretch", category: "Esneklik", description: "Kalça fleksör germe" },
  { name: "Chest Stretch", category: "Esneklik", description: "Göğüs germe" },
  { name: "Shoulder Stretch", category: "Esneklik", description: "Omuz germe" },
  { name: "Triceps Stretch", category: "Esneklik", description: "Triceps germe" },
  { name: "Lat Stretch", category: "Esneklik", description: "Sırt germe" },
  { name: "Cat-Cow Stretch", category: "Esneklik", description: "Kedi-inek hareketi" },
  { name: "Child Pose (Çocuk Pozu)", category: "Esneklik", description: "Çocuk pozu" },
  { name: "Pigeon Stretch", category: "Esneklik", description: "Güvercin pozu (kalça açma)" },
  { name: "World's Greatest Stretch", category: "Esneklik", description: "Dünyanın en iyi germe hareketi" },
  { name: "Foam Rolling", category: "Esneklik", description: "Foam roller ile miyofasyal gevşeme" },
  { name: "Band Pull-Apart", category: "Esneklik", description: "Bant ile omuz açma" },
  { name: "Wall Slide", category: "Esneklik", description: "Duvarda kol kaydırma (omuz mobilite)" },
  { name: "Calf Stretch", category: "Esneklik", description: "Baldır germe" },

  // ═══ FONKSİYONEL ═══
  { name: "Turkish Get-Up", category: "Fonksiyonel", description: "Türk kalkmesi (kettlebell)" },
  { name: "Clean & Press", category: "Fonksiyonel", description: "Yerden kaldırıp baş üstüne pres" },
  { name: "Snatch (Kettlebell)", category: "Fonksiyonel", description: "Kettlebell snatch" },
  { name: "Farmer's Walk", category: "Fonksiyonel", description: "Çiftçi yürüyüşü (ağırlık taşıma)" },
  { name: "Bear Crawl", category: "Fonksiyonel", description: "Ayı yürüyüşü" },
  { name: "Wall Ball", category: "Fonksiyonel", description: "Duvara top atma" },
  { name: "Thruster", category: "Fonksiyonel", description: "Squat + overhead press kombine" },
  { name: "Power Clean", category: "Fonksiyonel", description: "Barbell power clean" },
  { name: "Man Maker", category: "Fonksiyonel", description: "Dumbbell man maker (full body)" },
  { name: "Sandbag Carry", category: "Fonksiyonel", description: "Kum torbası taşıma" },
];
